name: Bug report
description: Report a *specific* issue
title: "[Bug]: <Enter descriptive title here>"
labels: bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you want to ask a general question about the menu, please open a new Discussion instead. I repeat, if this is NOT A BUG WITH THE MENU, do not open a bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs and/or screenshots
      description: |
        For a bug report to be valid, please include the logs for YimMenuV2.
        They can be found under `%appdata%/YimMenuV2/cout.log`, even if you think the log file is useless we'd still like for you to include it here.
        You MUST do this if you're reporting a crash. Attaching the DLL you used is also helpful

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      value: |
        ```
        <paste your logs here>
        ```
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Store
      description: Which launcher/store do you use to launch your game?
      multiple: false
      options:
        - Steam
        - Epic Games
        - Rockstar
        - Microsoft Store/Game Pass
        - Other (please mention in "Additional context")
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Anticheat bypass mode
      description: How do you use this menu?
      multiple: false
      options:
        - With FSL
        - Without FSL
        - With a custom BattlEye bypass
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Build
      description: We want to confirm that this issue exists on the latest version of YimMenuV2, not a fork or your own version of YimMenuV2.
      options:
        - label: I've confirmed the issue exists on the latest version of YimMenuV2
          required: true
  - type: checkboxes
    attributes:
      label: Duplicate
      description: You confirm that you've read existing open issues of YimMenuV2 and this isn't a duplicate of an already existing bug.
      options:
        - label: I confirm that issue isn't a duplicate.
          required: true
